param(
    [Parameter(Mandatory = $true)][string]$OutputPath,
    [Parameter(Mandatory = $true)][string]$RepoRoot
)

$hash = "unknown"
$date = "unknown"

if (Test-Path -LiteralPath $RepoRoot) {
    Push-Location -LiteralPath $RepoRoot
    try {
        $h = & git rev-parse --short HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $h) {
            $hash = ([string]$h).Trim()
        }
        $d = & git log -1 --format=%ci 2>$null
        if ($LASTEXITCODE -eq 0 -and $d) {
            $date = ([string]$d).Trim()
        }
    }
    finally {
        Pop-Location
    }
}

function Escape-CSharpString([string]$value) {
    return ($value -replace '\\', '\\' -replace '"', '\"')
}

$hashEsc = Escape-CSharpString $hash
$dateEsc = Escape-CSharpString $date

$nl = [Environment]::NewLine
$content = '// <auto-generated />' + $nl +
'// Generated at build time from the local git repository.' + $nl +
'namespace AtariMapMaker' + $nl +
'{' + $nl +
'    internal static class GitCommitInfo' + $nl +
'    {' + $nl +
'        public const string CommitHash = "' + $hashEsc + '";' + $nl +
'        public const string CommitDate = "' + $dateEsc + '";' + $nl +
'    }' + $nl +
'}' + $nl

$dir = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrEmpty($dir) -and -not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

Set-Content -LiteralPath $OutputPath -Value $content -Encoding UTF8
